// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksAPI.Models;

namespace ParksAPI.Migrations
{
    [DbContext(typeof(ParksAPIContext))]
    [Migration("20210711013636_Initial3")]
    partial class Initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParkLocation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkLocation = "Oregon",
                            ParkName = "Beaver Creek",
                            ParkType = "State Park"
                        },
                        new
                        {
                            ParkId = 2,
                            ParkLocation = "Oregon",
                            ParkName = "Prineville Reservior",
                            ParkType = "State Park"
                        },
                        new
                        {
                            ParkId = 3,
                            ParkLocation = "Oregon",
                            ParkName = "Willamette Mission",
                            ParkType = "State Park"
                        },
                        new
                        {
                            ParkId = 4,
                            ParkLocation = "Oregon",
                            ParkName = "Crater Lake",
                            ParkType = "National Park"
                        },
                        new
                        {
                            ParkId = 5,
                            ParkLocation = "California",
                            ParkName = "Death Valley",
                            ParkType = "National Park"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
